from fpdf import FPDF


def generate_pdf(data_user):
    pdf = FPDF()
    pdf.add_page()
    # header
    pdf.set_font('Times')
    pdf.cell(20, 5, f"{data_user['firstname']} {data_user['lastname']}", ln=1)
    pdf.cell(18, 5, "Portfolio :")
    pdf.set_text_color(9, 132, 227)
    pdf.set_font('Times', 'U', 12)
    pdf.cell(100, 5, data_user['portfolio'], ln=1)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times')
    pdf.cell(15, 5, "Github :")
    pdf.set_text_color(9, 132, 227)
    pdf.set_font('Times', 'U', 12)
    pdf.cell(100, 5, data_user['github'], ln=1)
    pdf.set_font('Times', '', 12)
    pdf.cell(0, 5, '', ln=1)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(180, 5, data_user['description'])
    # experience
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'BU', 16)
    pdf.cell(100, 20, 'Experience', ln=1)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(20, 5, f"{data_user['developerExperience']['job']}", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(20, 10, f"{data_user['developerExperience']['employer']} : {data_user['developerExperience']['date']}", ln=1)
    pdf.set_font('Times', '', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(180, 5, data_user['developerExperience']['description'])
    pdf.cell(1, 5, '', ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(9, 132, 227)
    pdf.cell(180, 5, f"{data_user['developerExperience']['skill']}", align='R')
    # Skill
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'BU', 16)
    pdf.cell(0, 0, '', align='R', ln=1)
    pdf.cell(100, 20, 'Skill', ln=1, align='L')
    pdf.set_font('Times', 'B', 12)
    pdf.cell(30, 6, "Language", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(9, 132, 227)
    pdf.multi_cell(180, 5, f"   {data_user['skill']['language']}")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(0, 2, "", ln=1)
    pdf.cell(30, 6, "Framework", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(9, 132, 227)
    pdf.multi_cell(180, 5, f"   {data_user['skill']['framework']}")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(0, 2, "", ln=1)
    pdf.cell(30, 6, "Tools", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(9, 132, 227)
    pdf.multi_cell(180, 5, f"   {data_user['skill']['tools']}")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(0, 2, "", ln=1)
    pdf.cell(30, 6, "System", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(9, 132, 227)
    pdf.multi_cell(180, 5, f"   {data_user['skill']['system']}")
    pdf.cell(0, 3, "", ln=1)
    # Project
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'BU', 16)
    pdf.cell(100, 20, 'Project', ln=1)
    pdf.set_font('Times', 'B', 12)
    pdf.cell(20, 5, f"{data_user['project']['title']}", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(20, 10, f"{data_user['project']['date']}", ln=1)
    pdf.set_font('Times', '', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(180, 5, data_user['project']['description'])
    pdf.cell(1, 5, '', ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(9, 132, 227)
    pdf.cell(180, 5, f"{data_user['project']['skill']}", align='R')
    # Project
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Times', 'BU', 16)
    pdf.cell(0, 0, '', ln=1, align='L')
    pdf.cell(100, 20, 'Degree', ln=1, align='L')
    pdf.set_font('Times', 'B', 12)
    pdf.cell(20, 5, f"{data_user['education']['degree']}", ln=1)
    pdf.set_font('Times', 'I', 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(20, 10, f"{data_user['education']['institution']} : {data_user['education']['date']}",
             ln=1)

    pdf.output('tuto.pdf', 'F')
